env:
  es6: true
  node: true
  mocha: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
extends:
  - 'plugin:vue/vue3-recommended'
  - 'prettier'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  '@typescript-eslint/no-explicit-any': off
