GET http://localhost:3000v/

###
GET http://localhost:3000/laws

###
POST http://localhost:3000/simulations


###
POST http://localhost:3000/simulations/257f679d-ec98-429b-a3fc-0413f8850a65/proposals/1


###
POST http://localhost:3000/simulations/257f679d-ec98-429b-a3fc-0413f8850a65/years